version: "3.7"
services:
  service:
    build: .
    command: ["streamlit", "run", "app.py"]
    ports:
      - 8501:8501
    volumes:
      - ${HOME}/.aws:/home/debian/.aws  # AWS Creds
      - ./:/home/debian/service  # This dir to workdir
